version: '3'

services:
  db:
    image: mysql:5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lemon-bubbles
    ports:
      - '3306:3306'